DECLARE FCH_HOY DATE DEFAULT CURRENT_DATE('America/Mexico_City');
DECLARE FCH_INI DATE DEFAULT (DATE_ADD(DATE_TRUNC(FCH_HOY, YEAR), INTERVAL -1 YEAR));
DECLARE FCH_FIN DEFAULT (LAST_DAY(DATE_TRUNC(FCH_HOY, YEAR), YEAR));

WITH 
VFAC_OMDM_FLUJO AS (
  SELECT 
    BR_SOLIC_CVE,
    MAX(BR_IMP_LIM_CRED_APROB) AS BR_IMP_LIM_CRED
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_OMDM_FLUJO`
  WHERE FCH_CARGA >= FCH_INI
    AND BR_ORG IN (200, 210, 230)
  GROUP BY 1
),

APIS AS (
  SELECT 
    BR_SOLIC_CVE,
    BR_TIPO,
    BR_STATUS
  FROM (
    SELECT 
      BR_SOLIC_CVE,
      BR_TIPO,
      BR_STATUS,
      ROW_NUMBER() OVER (
        PARTITION BY BR_SOLIC_CVE, BR_TIPO
        ORDER BY 
          CASE BR_STATUS
            WHEN 'T' THEN 5
            WHEN 'D' THEN 4
            WHEN 'A' THEN 3
            WHEN 'C' THEN 2
            ELSE 0
          END DESC
      ) AS rn
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIS`
    WHERE SYS_FTE = 75
      AND BR_ORG IN (200, 210, 230)
      AND FCH_CARGA >= FCH_INI
  )
  WHERE rn = 1
),

SOLICITUDES AS (
  SELECT
    a.BR_SOLIC_CVE,
    a.BR_TIPO,
    a.BR_ORG,
    a.SegmentoScore,
    a.BR_FCH_SOLIC,
    a.BR_SCORE_FIN,
    a.BR_HIT_CVE,
    b.BR_IMP_LIM_CRED,
    c.CTA_CVE,
    d.BR_EDAD,
    d.BR_SEXO,
    d.BR_ESCOLARIDAD,
    d.BR_ING_TOT,
    d.BR_EDC_CVE,
    d.BR_TIP_VDA,
    e.PTI,
    e.BTI,
    e.BR_TASA_CVE,
    e.IQ_NUM_CONS_3M,
    e.IQ_NUM_CONS_6M,
    e.TL_NUM_CTAS_TDC_ABT,
    e.TL_SUM_SDO_CTAS_TDC_ABT,
    e.BR_MODULO_SCORE_DES,
    -- Extraemos las nuevas variables de Buró solicitadas
    e.TL_MAX_MOP_CTAS_VAL_3M,
    e.TL_MAX_MOP_CTAS_VAL_6M,
    e.TL_MAX_MOP_CTAS_VAL_9M,
    e.TL_MAX_MOP_CTAS_VAL_12M,
    e.TL_MAX_MOP_CTAS_VAL_24M,
    
    b.BR_IMP_LIM_CRED/GREATEST(d.BR_ING_TOT,2000) AS LTI_ONUS,
    (b.BR_IMP_LIM_CRED+e.TL_SUM_LIM_CRED_CTAS_TDC_ABT)/GREATEST(d.BR_ING_TOT,2000) AS LTI_TOT,
    CASE 
      WHEN e.TL_NUM_CTAS_TDC_ABT = 0 THEN -999
      ELSE e.TL_SUM_LIM_CRED_CTAS_TDC_ABT/e.TL_NUM_CTAS_TDC_ABT 
    END AS LINEAS,
    CASE 
      WHEN e.TL_SUM_SDO_CTAS_TDC_ABT = 0 OR e.TL_SUM_LIM_CRED_CTAS_TDC_ABT = 0 THEN 0
      WHEN e.TL_SUM_SDO_CTAS_TDC_ABT/e.TL_SUM_LIM_CRED_CTAS_TDC_ABT>=1 THEN 1
      ELSE e.TL_SUM_SDO_CTAS_TDC_ABT/e.TL_SUM_LIM_CRED_CTAS_TDC_ABT 
    END AS Utilizacion,
    CASE
      WHEN a.BR_ORG = 210 THEN 'Departamental'
      WHEN a.BR_ORG = 230 THEN 'Minipagos'
      WHEN a.BR_ORG = 200 THEN 'VISA' 
    END AS Producto,
    CASE
      WHEN a.BR_TIPO IN (1001,1011,1021,1031) THEN 'X-Sell'
      WHEN a.BR_ORG = 200 AND a.BR_HIT_CVE = 1 AND a.SegmentoScore IN (10,16,33,34,35) THEN 'Doble'
      WHEN a.BR_ORG = 200 AND a.BR_HIT_CVE = 1 THEN 'Puro'
      WHEN a.BR_HIT_CVE = 1 THEN 'Hit'
      WHEN a.BR_HIT_CVE = 2 THEN 'No Hit'
      WHEN a.BR_HIT_CVE = 0 THEN 'Thin File'
      ELSE 'Sin Hit'
    END AS Segmento,
    CASE
      WHEN a.BR_FCH_SOLIC BETWEEN '2024-05-15' AND '2024-05-23' THEN 'HotSale 24'
      WHEN a.BR_FCH_SOLIC BETWEEN '2024-10-18' AND '2024-10-20' THEN 'NochesMoradas Oct24'
      WHEN a.BR_FCH_SOLIC BETWEEN '2024-11-15' AND '2024-11-18' THEN 'BuenFin 24'
      WHEN a.BR_FCH_SOLIC BETWEEN '2024-11-29' AND '2024-12-02' THEN 'BlackDays 24'
      WHEN a.BR_FCH_SOLIC BETWEEN '2024-12-05' AND '2024-12-08' THEN 'NochesMoradas Dec24'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-05-01' AND '2025-05-04' THEN 'VentaMamas 25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-05-25' AND '2025-06-03' THEN 'HotSale 25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-10-17' AND '2025-10-19' THEN 'NochesMoradas Oct25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-11-07' AND '2025-11-09' THEN 'Pre-venta 25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-11-13' AND '2025-11-17' THEN 'BuenFin 25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-11-28' AND '2025-12-01' THEN 'BlackDays 25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2025-12-05' AND '2025-12-07' THEN 'NochesMoradas Dec25'
      WHEN a.BR_FCH_SOLIC BETWEEN '2026-04-30' AND '2026-05-03' THEN 'VentaMamas 26'
      WHEN a.BR_FCH_SOLIC BETWEEN '2026-05-25' AND '2026-06-02' THEN 'HotSale 26'
      WHEN a.BR_FCH_SOLIC BETWEEN '2026-06-05' AND '2026-06-07' THEN 'VentaPapas 26'
      ELSE 'BAU'
    END AS Temp_Venta,
    CASE
      WHEN a.SegmentoScore=13 AND BR_SCORE_FIN <= 230 THEN 5
      WHEN a.SegmentoScore=13 AND BR_SCORE_FIN <= 248 THEN 4
      WHEN a.SegmentoScore=13 AND BR_SCORE_FIN <= 255 THEN 3
      WHEN a.SegmentoScore=13 AND BR_SCORE_FIN <= 271 THEN 2
      WHEN a.SegmentoScore=13 AND BR_SCORE_FIN > 271 THEN 1
      WHEN a.SegmentoScore=16 AND BR_SCORE_FIN <= 245 THEN 5
      WHEN a.SegmentoScore=16 AND BR_SCORE_FIN <= 254 THEN 4
      WHEN a.SegmentoScore=16 AND BR_SCORE_FIN <= 261 THEN 3
      WHEN a.SegmentoScore=16 AND BR_SCORE_FIN <= 268 THEN 2
      WHEN a.SegmentoScore=16 AND BR_SCORE_FIN > 268 THEN 1
      WHEN a.SegmentoScore=18 AND BR_SCORE_FIN < 237  THEN 5
      WHEN a.SegmentoScore=18 AND BR_SCORE_FIN < 249  THEN 4
      WHEN a.SegmentoScore=18 AND BR_SCORE_FIN < 264  THEN 3
      WHEN a.SegmentoScore=18 AND BR_SCORE_FIN < 274  THEN 2
      WHEN a.SegmentoScore=18 AND BR_SCORE_FIN >= 274 THEN 1
      WHEN a.SegmentoScore=19 AND BR_SCORE_FIN < 243  THEN 5
      WHEN a.SegmentoScore=19 AND BR_SCORE_FIN < 250  THEN 4
      WHEN a.SegmentoScore=19 AND BR_SCORE_FIN < 255  THEN 3
      WHEN a.SegmentoScore=19 AND BR_SCORE_FIN < 264  THEN 2
      WHEN a.SegmentoScore=19 AND BR_SCORE_FIN >= 264 THEN 1
      WHEN a.SegmentoScore=20 AND BR_SCORE_FIN < 237  THEN 5
      WHEN a.SegmentoScore=20 AND BR_SCORE_FIN < 247  THEN 4
      WHEN a.SegmentoScore=20 AND BR_SCORE_FIN < 252  THEN 3
      WHEN a.SegmentoScore=20 AND BR_SCORE_FIN >= 252 THEN 2
      WHEN a.SegmentoScore=21 AND BR_SCORE_FIN < 234  THEN 5
      WHEN a.SegmentoScore=21 AND BR_SCORE_FIN < 249  THEN 4
      WHEN a.SegmentoScore=21 AND BR_SCORE_FIN < 264  THEN 3
      WHEN a.SegmentoScore=21 AND BR_SCORE_FIN < 274  THEN 2
      WHEN a.SegmentoScore=21 AND BR_SCORE_FIN >= 274 THEN 1
      WHEN a.SegmentoScore=22 AND BR_SCORE_FIN < 230  THEN 5
      WHEN a.SegmentoScore=22 AND BR_SCORE_FIN < 236  THEN 4
      WHEN a.SegmentoScore=22 AND BR_SCORE_FIN < 246  THEN 3
      WHEN a.SegmentoScore=22 AND BR_SCORE_FIN < 256  THEN 2
      WHEN a.SegmentoScore=22 AND BR_SCORE_FIN >= 256 THEN 1
      WHEN a.SegmentoScore=23 AND BR_SCORE_FIN < 228  THEN 5
      WHEN a.SegmentoScore=23 AND BR_SCORE_FIN < 240  THEN 4
      WHEN a.SegmentoScore=23 AND BR_SCORE_FIN < 251  THEN 3
      WHEN a.SegmentoScore=23 AND BR_SCORE_FIN < 260  THEN 2
      WHEN a.SegmentoScore=23 AND BR_SCORE_FIN >= 260 THEN 1
      WHEN a.SegmentoScore=24 AND BR_SCORE_FIN < 240  THEN 5
      WHEN a.SegmentoScore=24 AND BR_SCORE_FIN < 241  THEN 4
      WHEN a.SegmentoScore=24 AND BR_SCORE_FIN < 246  THEN 3
      WHEN a.SegmentoScore=24 AND BR_SCORE_FIN < 261  THEN 2
      WHEN a.SegmentoScore=24 AND BR_SCORE_FIN >= 261 THEN 1
      WHEN a.SegmentoScore=33 AND BR_SCORE_FIN BETWEEN 0   AND 248 THEN 5
      WHEN a.SegmentoScore=33 AND BR_SCORE_FIN BETWEEN 249 AND 266 THEN 4
      WHEN a.SegmentoScore=33 AND BR_SCORE_FIN BETWEEN 267 AND 280 THEN 3
      WHEN a.SegmentoScore=33 AND BR_SCORE_FIN BETWEEN 281 AND 294 THEN 2
      WHEN a.SegmentoScore=33 AND BR_SCORE_FIN >= 295              THEN 1
      WHEN a.SegmentoScore=34 AND BR_SCORE_FIN BETWEEN 0   AND 246 THEN 5
      WHEN a.SegmentoScore=34 AND BR_SCORE_FIN BETWEEN 247 AND 259 THEN 4
      WHEN a.SegmentoScore=34 AND BR_SCORE_FIN BETWEEN 260 AND 265 THEN 3
      WHEN a.SegmentoScore=34 AND BR_SCORE_FIN BETWEEN 266 AND 287 THEN 2
      WHEN a.SegmentoScore=34 AND BR_SCORE_FIN >= 288              THEN 1
      WHEN a.SegmentoScore=35 AND BR_SCORE_FIN BETWEEN 0   AND 236 THEN 5
      WHEN a.SegmentoScore=35 AND BR_SCORE_FIN BETWEEN 237 AND 254 THEN 4
      WHEN a.SegmentoScore=35 AND BR_SCORE_FIN BETWEEN 255 AND 268 THEN 3
      WHEN a.SegmentoScore=35 AND BR_SCORE_FIN BETWEEN 269 AND 285 THEN 2
      WHEN a.SegmentoScore=35 AND BR_SCORE_FIN >= 286              THEN 1
      WHEN a.SegmentoScore=36 AND BR_SCORE_FIN BETWEEN 0   AND 236 THEN 5 
      WHEN a.SegmentoScore=36 AND BR_SCORE_FIN BETWEEN 237 AND 254 THEN 4
      WHEN a.SegmentoScore=36 AND BR_SCORE_FIN BETWEEN 255 AND 268 THEN 3
      WHEN a.SegmentoScore=36 AND BR_SCORE_FIN BETWEEN 269 AND 285 THEN 2
      WHEN a.SegmentoScore=36 AND BR_SCORE_FIN >= 286              THEN 1
      ELSE -999
    END AS RiskLevel
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_OMDM_SOLICITUD` a
  LEFT JOIN VFAC_OMDM_FLUJO b USING(BR_SOLIC_CVE)
  LEFT JOIN (
    SELECT
      CTA_CVE,
      BR_SOLIC_CVE,
      BR_TIPO,
      CTA_FCH_ALTA
    FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA`
    WHERE CTA_FCH_ALTA >= FCH_INI
      AND TIP_INF IN (200,210,230)
    ) c
  ON a.BR_SOLIC_CVE = c.BR_SOLIC_CVE
  AND CAST(SUBSTR(CAST(a.BR_TIPO AS STRING),1,3) AS NUMERIC) = c.BR_TIPO
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_APIA` d
  ON a.BR_SOLIC_CVE = d.BR_SOLIC_CVE AND a.BR_TIPO = d.BR_TIPO
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_SOLICITUDES` e
  ON a.BR_SOLIC_CVE = e.BR_SOLIC_CVE AND a.BR_TIPO = e.BR_TIPO
  LEFT JOIN APIS f
  ON a.BR_SOLIC_CVE = f.BR_SOLIC_CVE AND a.BR_TIPO = f.BR_TIPO
  WHERE a.BR_ORG IN (200, 210, 230)
    AND a.BR_FCH_SOLIC >= FCH_INI
),

MUESTRA_PREPARADA AS (
  SELECT
    FORMAT_DATE('%Y-%m', BR_FCH_SOLIC) AS PERIODO,
    Producto,
    COALESCE(BR_MODULO_SCORE_DES, 'Otros/Null') AS Modelo,
    CAST(RiskLevel AS STRING) AS RiskLevel, 
    IF(BR_HIT_CVE = 2, 'NoHit', 'Hit') AS Flag_NoHit,
    IF(BR_SEXO = 'F', 'Mujer', 'Hombre') AS Flag_Femenino,
    
    CASE 
      WHEN PTI >= 0 AND PTI < 0.03 THEN '0%-3%'
      WHEN PTI >= 0.03 AND PTI < 0.06 THEN '3%-6%'
      WHEN PTI >= 0.06 AND PTI < 0.09 THEN '6%-9%'
      WHEN PTI >= 0.09 AND PTI < 0.12 THEN '9%-12%'
      WHEN PTI >= 0.12 AND PTI < 0.15 THEN '12%-15%'
      WHEN PTI >= 0.15 THEN '15%+'
      ELSE 'Otros/Null'
    END AS PTI,

    CASE 
      WHEN BTI >= 0 AND BTI < 0.20    THEN '0-0.20'
      WHEN BTI >= 0.20 AND BTI < 0.40 THEN '0.20-0.40'
      WHEN BTI >= 0.40 AND BTI < 0.60 THEN '0.40-0.60'
      WHEN BTI >= 0.60 AND BTI < 0.80 THEN '0.60-0.80'
      WHEN BTI >= 0.80 AND BTI < 1    THEN '0.80-1'
      WHEN BTI >= 1 AND BTI < 1.2     THEN '1-1.2'
      WHEN BTI >= 1.2 AND BTI < 1.4   THEN '1.2-1.4'
      WHEN BTI >= 1.4 AND BTI < 1.6   THEN '1.4-1.6'
      WHEN BTI >= 1.6 AND BTI < 1.8   THEN '1.6-1.8'
      WHEN BTI >= 1.8 AND BTI < 2     THEN '1.8-2'
      WHEN BTI >= 2 THEN '2+'
      ELSE 'Otros/Null'
    END AS BTI,

    CASE 
      WHEN LTI_ONUS >= 0 AND LTI_ONUS < 0.20 THEN '0-0.20'
      WHEN LTI_ONUS >= 0.20 AND LTI_ONUS < 0.40 THEN '0.20-0.40'
      WHEN LTI_ONUS >= 0.40 AND LTI_ONUS < 0.60 THEN '0.40-0.60'
      WHEN LTI_ONUS >= 0.60 AND LTI_ONUS < 0.80 THEN '0.60-0.80'
      WHEN LTI_ONUS >= 0.80 AND LTI_ONUS < 1 THEN '0.80-1'
      WHEN LTI_ONUS >= 1 AND LTI_ONUS < 1.2 THEN '1-1.2'
      WHEN LTI_ONUS >= 1.2 AND LTI_ONUS < 1.4 THEN '1.2-1.4'
      WHEN LTI_ONUS >= 1.4 AND LTI_ONUS < 1.6 THEN '1.4-1.6'
      WHEN LTI_ONUS >= 1.6 AND LTI_ONUS < 1.8 THEN '1.6-1.8'
      WHEN LTI_ONUS >= 1.8 AND LTI_ONUS < 2 THEN '1.8-2'
      WHEN LTI_ONUS >= 2 THEN '2+'
      ELSE 'Otros/Null'
    END AS LTI_ONUS,

    CASE 
      WHEN LTI_TOT >= 0 AND LTI_TOT < 2 THEN '0-2'
      WHEN LTI_TOT >= 2 AND LTI_TOT < 4 THEN '2-4'
      WHEN LTI_TOT >= 4 AND LTI_TOT < 6 THEN '4-6'
      WHEN LTI_TOT >= 6 AND LTI_TOT < 8 THEN '6-8'
      WHEN LTI_TOT >= 8 THEN '8+'
      ELSE 'Otros/Null'
    END AS LTI_TOT,

    CASE
      WHEN IQ_NUM_CONS_3M = 0 THEN '0'
      WHEN IQ_NUM_CONS_3M = 1 THEN '1'
      WHEN IQ_NUM_CONS_3M = 2 THEN '2'
      WHEN IQ_NUM_CONS_3M = 3 THEN '3'
      WHEN IQ_NUM_CONS_3M = 4 THEN '4'
      WHEN IQ_NUM_CONS_3M = 5 THEN '5'
      WHEN IQ_NUM_CONS_3M >= 6 THEN '6+'
      ELSE 'Otros/Null'
    END AS Consultas_3M,

    CASE
      WHEN IQ_NUM_CONS_6M = 0 THEN '0'
      WHEN IQ_NUM_CONS_6M = 1 THEN '1'
      WHEN IQ_NUM_CONS_6M = 2 THEN '2'
      WHEN IQ_NUM_CONS_6M = 3 THEN '3'
      WHEN IQ_NUM_CONS_6M = 4 THEN '4'
      WHEN IQ_NUM_CONS_6M = 5 THEN '5'
      WHEN IQ_NUM_CONS_6M >= 6 THEN '6+'
      ELSE 'Otros/Null'
    END AS Consultas_6M,

    CASE
      WHEN TL_NUM_CTAS_TDC_ABT = 1 THEN '1'
      WHEN TL_NUM_CTAS_TDC_ABT = 2 THEN '2'
      WHEN TL_NUM_CTAS_TDC_ABT = 3 THEN '3'
      WHEN TL_NUM_CTAS_TDC_ABT = 4 THEN '4'
      WHEN TL_NUM_CTAS_TDC_ABT = 5 THEN '5'
      WHEN TL_NUM_CTAS_TDC_ABT = 6 THEN '6'
      WHEN TL_NUM_CTAS_TDC_ABT = 7 THEN '7'
      WHEN TL_NUM_CTAS_TDC_ABT >= 8 THEN '8+'
      ELSE 'Otros/Null'
    END AS Numero_tarjetas,

    CASE 
      WHEN CAST(BR_EDC_CVE AS STRING) = '2' THEN 'Casado'
      WHEN CAST(BR_EDC_CVE AS STRING) = '1' THEN 'Soltero'
      ELSE 'Sin informacion'
    END AS Estado_Civil,

    CASE 
      WHEN CAST(BR_TIP_VDA AS STRING) = '1' THEN 'Propia'
      WHEN CAST(BR_TIP_VDA AS STRING) = '2' THEN 'Rentada/Hipotecada'
      WHEN CAST(BR_TIP_VDA AS STRING) = '3' THEN 'Familiar'
      ELSE 'Sin informacion'
    END AS Vivienda,
    
    CASE 
      WHEN CAST(BR_ESCOLARIDAD AS STRING) = '1' THEN 'Preparatoria'
      WHEN CAST(BR_ESCOLARIDAD AS STRING) = '2' THEN 'Técnica/ Comercial'
      WHEN CAST(BR_ESCOLARIDAD AS STRING) = '3' THEN 'Licenciatura'
      WHEN CAST(BR_ESCOLARIDAD AS STRING) = '4' THEN 'Posgrado'
      WHEN CAST(BR_ESCOLARIDAD AS STRING) = '5' THEN 'Otro'
      ELSE 'Sin informacion'
    END AS Escolaridad,

    -- =========================================================================
    -- NUEVO MAPEO DE MOPs SOLICITADO (3M, 6M, 9M, 12M, 24M)
    -- =========================================================================
    CASE 
      WHEN TL_MAX_MOP_CTAS_VAL_3M BETWEEN 1 AND 7 THEN CAST(TL_MAX_MOP_CTAS_VAL_3M AS STRING)
      WHEN TL_MAX_MOP_CTAS_VAL_3M IN (8, 9, 10) THEN '8-10'
      WHEN TL_MAX_MOP_CTAS_VAL_3M IN (96, 97, 99) THEN '96-99'
      ELSE 'Otros/Null'
    END AS Mop_Max_3M,

    CASE 
      WHEN TL_MAX_MOP_CTAS_VAL_6M BETWEEN 1 AND 7 THEN CAST(TL_MAX_MOP_CTAS_VAL_6M AS STRING)
      WHEN TL_MAX_MOP_CTAS_VAL_6M IN (8, 9, 10) THEN '8-10'
      WHEN TL_MAX_MOP_CTAS_VAL_6M IN (96, 97, 99) THEN '96-99'
      ELSE 'Otros/Null'
    END AS Mop_Max_6M,

    CASE 
      WHEN TL_MAX_MOP_CTAS_VAL_9M BETWEEN 1 AND 7 THEN CAST(TL_MAX_MOP_CTAS_VAL_9M AS STRING)
      WHEN TL_MAX_MOP_CTAS_VAL_9M IN (8, 9, 10) THEN '8-10'
      WHEN TL_MAX_MOP_CTAS_VAL_9M IN (96, 97, 99) THEN '96-99'
      ELSE 'Otros/Null'
    END AS Mop_Max_9M,

    CASE 
      WHEN TL_MAX_MOP_CTAS_VAL_12M BETWEEN 1 AND 7 THEN CAST(TL_MAX_MOP_CTAS_VAL_12M AS STRING)
      WHEN TL_MAX_MOP_CTAS_VAL_12M IN (8, 9, 10) THEN '8-10'
      WHEN TL_MAX_MOP_CTAS_VAL_12M IN (96, 97, 99) THEN '96-99'
      ELSE 'Otros/Null'
    END AS Mop_Max_12M,

    CASE 
      WHEN TL_MAX_MOP_CTAS_VAL_24M BETWEEN 1 AND 7 THEN CAST(TL_MAX_MOP_CTAS_VAL_24M AS STRING)
      WHEN TL_MAX_MOP_CTAS_VAL_24M IN (8, 9, 10) THEN '8-10'
      WHEN TL_MAX_MOP_CTAS_VAL_24M IN (96, 97, 99) THEN '96-99'
      ELSE 'Otros/Null'
    END AS Mop_Max_24M,
    
    CASE
      -- VISA
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 216 THEN '[-,216)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 226 THEN '[216,226)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 233 THEN '[226,233)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 241 THEN '[233,241)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 247 THEN '[241,247)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 255 THEN '[247,255)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 261 THEN '[255,261)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 269 THEN '[261,269)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN < 278 THEN '[269,278)'
      WHEN Producto = 'VISA' AND SegmentoScore IN (35, 36) AND BR_SCORE_FIN >= 278 THEN '[278,+)'

      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 226 THEN '[-,226)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 240 THEN '[226,240)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 249 THEN '[240,249)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 256 THEN '[249,256)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 264 THEN '[256,264)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 270 THEN '[264,270)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 277 THEN '[270,277)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 285 THEN '[277,285)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN < 295 THEN '[285,295)'
      WHEN Producto = 'VISA' AND SegmentoScore = 33 AND BR_SCORE_FIN >= 295 THEN '[295,+)'

      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 215 THEN '[-,215)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 227 THEN '[215,227)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 236 THEN '[227,236)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 243 THEN '[236,243)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 250 THEN '[243,250)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 256 THEN '[250,256)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 263 THEN '[256,263)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 270 THEN '[263,270)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN < 281 THEN '[270,281)'
      WHEN Producto = 'VISA' AND SegmentoScore = 34 AND BR_SCORE_FIN >= 281 THEN '[281,+)'

       -- -----------------------------------------------------------------------
      -- GRUPO B: DEPARTAMENTAL (BR_ORG = 210) - HIT
      -- -----------------------------------------------------------------------
      /* ThickRev */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 217 THEN '[-,216)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 230 THEN '[217,229)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 241 THEN '[230,240)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 251 THEN '[241,250)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 261 THEN '[251,260)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 270 THEN '[261,269)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 279 THEN '[270,278)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 290 THEN '[279,289)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 302 THEN '[290,301)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN >= 302 THEN '[302,+)'

      /* ThinRevTLAgeLT30 */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 195 THEN '[-,194)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 208 THEN '[195,207)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 216 THEN '[208,215)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 221 THEN '[216,220)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 227 THEN '[221,226)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 235 THEN '[227,234)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 240 THEN '[235,239)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 245 THEN '[240,244)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 247 THEN '[245,247)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN >= 247 THEN '[247,+)'

      /* ThinRevAgeGE30 */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 198 THEN '[-,197)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 213 THEN '[198,212)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 223 THEN '[213,222)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 232 THEN '[223,231)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 240 THEN '[232,239)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 248 THEN '[240,247)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 255 THEN '[248,254)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 264 THEN '[255,263)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 274 THEN '[264,273)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN >= 274 THEN '[274,+)'

      /* NewToRevolving */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 177 THEN '[-,177)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 187 THEN '[177,187)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 194 THEN '[187,194)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 200 THEN '[194,200)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 206 THEN '[200,206)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 211 THEN '[206,211)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 218 THEN '[211,218)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 225 THEN '[218,225)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 235 THEN '[225,235)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN >= 235 THEN '[235,+)'

      -- -----------------------------------------------------------------------
      -- GRUPO C: DEPARTAMENTAL (BR_ORG = 210) - NO HIT
      -- -----------------------------------------------------------------------
      /* ClsdRev */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 203 THEN '[-,203)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 216 THEN '[203,216)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 224 THEN '[216,224)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 231 THEN '[224,231)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 237 THEN '[231,237)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 244 THEN '[237,244)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 252 THEN '[244,252)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 262 THEN '[252,262)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 273 THEN '[262,273)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN >= 273 THEN '[273,+)'

      /* NRevAgeLT30 */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 194 THEN '[-,194)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 200 THEN '[194,200)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 207 THEN '[200,207)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 216 THEN '[207,216)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 223 THEN '[216,223)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 227 THEN '[223,227)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 234 THEN '[227,234)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 240 THEN '[234,240)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 251 THEN '[240,251)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN >= 251 THEN '[251,+)'

      /* NRevAgeGE30 */
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 217 THEN '[-,216)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 230 THEN '[217,230)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 240 THEN '[230,240)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 251 THEN '[241,251)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 260 THEN '[251,260)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 270 THEN '[261,270)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 278 THEN '[270,278)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 290 THEN '[279,290)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 302 THEN '[290,302)'
      WHEN Producto = 'Departamental' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN >= 302 THEN '[302,+)'

      -- -----------------------------------------------------------------------
      -- GRUPO D: MINIPAGOS (BR_ORG = 230) - HOMOLOGACIÓN DE SCORECARDS (HIT/NOHIT)
      -- -----------------------------------------------------------------------
      /* ThickRev */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 217 THEN '[-,216)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 230 THEN '[217,229)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 241 THEN '[230,240)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 251 THEN '[241,250)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 261 THEN '[251,260)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 270 THEN '[261,269)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 279 THEN '[270,278)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 290 THEN '[279,289)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN < 302 THEN '[290,301)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THICKREV' AND BR_SCORE_FIN >= 302 THEN '[302,+)'

      /* ThinRevTLAgeLT30 */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 195 THEN '[-,194)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 208 THEN '[195,207)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 216 THEN '[208,215)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 221 THEN '[216,220)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 227 THEN '[221,226)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 235 THEN '[227,234)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 240 THEN '[235,239)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 245 THEN '[240,244)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN < 247 THEN '[245,247)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVTLAGELT30' AND BR_SCORE_FIN >= 247 THEN '[247,+)'

      /* ThinRevAgeGE30 */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 198 THEN '[-,197)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 213 THEN '[198,212)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 223 THEN '[213,222)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 232 THEN '[223,231)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 240 THEN '[232,239)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 248 THEN '[240,247)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 255 THEN '[248,254)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 264 THEN '[255,263)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN < 274 THEN '[264,273)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_THINREVAGEGE30' AND BR_SCORE_FIN >= 274 THEN '[274,+)'

      /* NewToRevolving */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 177 THEN '[-,177)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 187 THEN '[177,187)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 194 THEN '[187,194)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 200 THEN '[194,200)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 206 THEN '[200,206)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 211 THEN '[206,211)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 218 THEN '[211,218)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 225 THEN '[218,225)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN < 235 THEN '[225,235)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBHIT_NEWTOREVOLVING' AND BR_SCORE_FIN >= 235 THEN '[235,+)'

      /* ClsdRev */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 203 THEN '[-,203)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 216 THEN '[203,216)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 224 THEN '[216,224)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 231 THEN '[224,231)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 237 THEN '[231,237)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 244 THEN '[237,244)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 252 THEN '[244,252)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 262 THEN '[252,262)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN < 273 THEN '[262,273)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHIT_CLSDREVTL' AND BR_SCORE_FIN >= 273 THEN '[273,+)'

      /* NRevAgeLT30 */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 194 THEN '[-,194)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 200 THEN '[194,200)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 207 THEN '[200,207)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 216 THEN '[207,216)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 223 THEN '[216,223)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 227 THEN '[223,227)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 234 THEN '[227,234)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 240 THEN '[234,240)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN < 251 THEN '[240,251)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGELT30' AND BR_SCORE_FIN >= 251 THEN '[251,+)'

      /* NRevAgeGE30 */
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 217 THEN '[-,216)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 230 THEN '[217,230)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 240 THEN '[230,240)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 251 THEN '[241,251)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 260 THEN '[251,260)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 270 THEN '[261,270)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 278 THEN '[270,278)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 290 THEN '[279,290)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN < 302 THEN '[290,302)'
      WHEN Producto = 'Minipagos' AND BR_MODULO_SCORE_DES = 'SCORECARDSBBNOHITNREV_AGEGE30' AND BR_SCORE_FIN >= 302 THEN '[302,+)'


    END AS Score,
    
    CASE 
      WHEN BR_EDAD < 25 THEN '< 25'
      WHEN BR_EDAD >= 25 AND BR_EDAD < 40 THEN '25 - 39'
      WHEN BR_EDAD >= 40 AND BR_EDAD < 55 THEN '40 - 54'
      WHEN BR_EDAD >= 55 AND BR_EDAD < 70 THEN '55 - 69'
      WHEN BR_EDAD >= 70 THEN '70+'
      ELSE 'Otros/Null'
    END AS Edad,
    
    CASE 
      WHEN BR_ING_TOT >= 0 AND BR_ING_TOT < 10000 THEN '0k - 10k'
      WHEN BR_ING_TOT >= 10000 AND BR_ING_TOT < 15000 THEN '10k - 15k'
      WHEN BR_ING_TOT >= 15000 AND BR_ING_TOT < 20000 THEN '15k - 20k'
      WHEN BR_ING_TOT >= 20000 AND BR_ING_TOT < 25000 THEN '20k - 25k'
      WHEN BR_ING_TOT >= 25000 AND BR_ING_TOT < 30000 THEN '25k - 30k'
      WHEN BR_ING_TOT >= 30000 AND BR_ING_TOT < 35000 THEN '30k - 35k'
      WHEN BR_ING_TOT >= 35000 THEN '35k+'
      ELSE 'Otros/Null'
    END AS Ingreso,
    
    CASE 
      WHEN BR_IMP_LIM_CRED >= 0 AND BR_IMP_LIM_CRED < 10000 THEN '0k - 10k'
      WHEN BR_IMP_LIM_CRED >= 10000 AND BR_IMP_LIM_CRED < 15000 THEN '10k - 15k'
      WHEN BR_IMP_LIM_CRED >= 15000 AND BR_IMP_LIM_CRED < 20000 THEN '15k - 20k'
      WHEN BR_IMP_LIM_CRED >= 20000 AND BR_IMP_LIM_CRED < 25000 THEN '20k - 25k'
      WHEN BR_IMP_LIM_CRED >= 25000 AND BR_IMP_LIM_CRED < 30000 THEN '25k - 30k'
      WHEN BR_IMP_LIM_CRED >= 30000 AND BR_IMP_LIM_CRED < 35000 THEN '30k - 35k'
      WHEN BR_IMP_LIM_CRED >= 35000 THEN '35k+'
      ELSE 'Otros/Null'
    END AS Linea_Credito_OnUs,
    
    CASE 
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 0 AND IF(LINEAS > 0, LINEAS, 0) < 10000 THEN '0k - 10k'
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 10000 AND IF(LINEAS > 0, LINEAS, 0) < 15000 THEN '10k - 15k'
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 15000 AND IF(LINEAS > 0, LINEAS, 0) < 20000 THEN '15k - 20k'
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 20000 AND IF(LINEAS > 0, LINEAS, 0) < 25000 THEN '20k - 25k'
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 25000 AND IF(LINEAS > 0, LINEAS, 0) < 30000 THEN '25k - 30k'
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 30000 AND IF(LINEAS > 0, LINEAS, 0) < 35000 THEN '30k - 35k'
      WHEN IF(LINEAS > 0, LINEAS, 0) >= 35000 THEN '35k+'
      ELSE 'Otros/Null'
    END AS Linea_Credito_OffUs,
    
    CASE
      WHEN Utilizacion = 0 THEN '0%'
      WHEN Utilizacion > 0 AND Utilizacion <= 0.30 THEN '1% - 30%'
      WHEN Utilizacion > 0.30 AND Utilizacion <= 0.60 THEN '31% - 60%'
      WHEN Utilizacion > 0.60 AND Utilizacion <= 0.90 THEN '61% - 90%'
      ELSE '91% - 100%'
    END AS Utilizacion,
    
    CAST(BR_TASA_CVE AS STRING) AS Tasa

  FROM SOLICITUDES
  WHERE CTA_CVE > 0 
  AND RiskLevel != -999
   
),

-- UNPIVOT: Transposición de las 25 variables de negocio a estructura agregada vertical (Incluyendo los 5 bines de MOPs)
MUESTRA_UNPIVOTED AS (
  SELECT 
    PERIODO,
    Producto,
    Modelo,
    variable,
    valor_categoria
  FROM MUESTRA_PREPARADA
  UNPIVOT(
    valor_categoria FOR variable IN (
      RiskLevel, Flag_NoHit, Flag_Femenino, Estado_Civil, Vivienda, Escolaridad, 
      Score, Edad, Ingreso, Linea_Credito_OnUs, Linea_Credito_OffUs, Utilizacion, 
      Tasa, PTI, BTI, LTI_ONUS, LTI_TOT, Consultas_3M, Consultas_6M, Numero_tarjetas,
      Mop_Max_3M, Mop_Max_6M, Mop_Max_9M, Mop_Max_12M, Mop_Max_24M
    )
  )
)

-- AGREGACIÓN FINAL DE VOLUMEN (100% Sin Muestreos en BigQuery)
SELECT 
  PERIODO AS Periodo,
  Producto,
  Modelo,
  variable AS Variable,
  valor_categoria AS Valor_Categoria,
  COUNT(*) AS Conteo
FROM MUESTRA_UNPIVOTED
GROUP BY 1, 2, 3, 4, 5
ORDER BY Periodo DESC, Producto, Modelo, Variable, Valor_Categoria;
